version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - redis
    #environment:
      #REDIS_URL: "redis://redis:6379/0"  #0 index of db
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
